### ISSUE TITLE
Terraform output

### ISSUE THREAD

**Issue by Yslamguly** [Yslamguly/VURYGE#5]
Dear Mr @s1mark ,

I tried to output the task-2 by running the following command `terraform output` even by specifying the name of the output. However, it gives me the following error:

> Warning: No outputs found
│ 
│ The state file either has no outputs defined, or all the defined outputs are empty. Please define an output in your configuration with the `output` keyword
│ and run `terraform refresh` for it to become available. If you are using interpolation, please verify the interpolated value is not empty. You can use the
│ `terraform console` command to assist.

Of course I run `terraform output` after applying the following commands:

- terraform init
- terraform plan
- terraform apply

But still the same warning.

Therefore, to make sure that I access "files" module from "read" module I create new files with prefix.

If you have time, could please shortly explain me why I cannot output?

**Comment by s1mark** [comment]
Hi @Yslamguly ,

Yes you are right! Sorry for being late checking your codebase. 
In your test answer you should revisit the question 2 and 4.
But beside of this and the formatting of your answers everything is okay

**Comment by Yslamguly** [comment]
Thank you for your response! I have corrected the answers. Hopefully they are correct!
